### ISSUE TITLE
关于amiyabot

### ISSUE THREAD

**Issue by desktop4025** [hsyhhssyy/amiyabot-arknights-hsyhhssyy-maa#1]
想问问amiya_bot_plugin_path中的plugin是下哪个啊

**Comment by hsyhhssyy** [comment]
哈？

**Comment by hsyhhssyy** [comment]
amiya_bot_plugin_path只是我的一个个人测试用脚本里的变量

此外，这个插件没有开发完，也有代码没有提交，你fork过去有啥用？

**Comment by desktop4025** [comment]
> amiya_bot_plugin_path只是我的一个个人测试用脚本里的变量
> 
> 此外，这个插件没有开发完，也有代码没有提交，你fork过去有啥用？

确实，今天再看了看发现了这是个插件。。是我的问题，但我又遇到了问题。。我把插件放plugins里面了但控制台看不到这个插件。。是本来就看不到还是说是我这边的问题？
![图片](https://user-images.githubusercontent.com/107090995/236247882-338b5326-a9fd-4945-8011-2764d76ccde3.png)
![图片](https://user-images.githubusercontent.com/107090995/236247918-119e50c1-3257-4035-b4da-e6314dda8840.png)

**Comment by hsyhhssyy** [comment]
我觉得是你的问题，要不你试试把文件夹改名叫 amiyabot-arknights-hsyhhssyy-maa-1_0

**Comment by desktop4025** [comment]
> 我觉得是你的问题，要不你试试把文件夹改名叫 amiyabot-arknights-hsyhhssyy-maa-1_0

还是没有欸，奇怪的是我看了看只有在插件页面安装的才能看到，我之前试了试直接把压缩包放里面野没有显示。。是不是我bot设置的问题啊。。

**Comment by desktop4025** [comment]
我看了一下日志安装这个插件好像出错了。。
![图片](https://user-images.githubusercontent.com/107090995/236258863-6514bde4-7dbc-4f66-80bb-f083c66684dc.png)

**Comment by desktop4025** [comment]
> 我觉得是你的问题，要不你试试把文件夹改名叫 amiyabot-arknights-hsyhhssyy-maa-1_0

修好了，是代码上好像出了点问题，加一个判断就好了，之前没有设置过密码的话会抛TypeError异常，改了下就装上了

        serve_conf = read_yaml('config/server.yaml')
        if serve_conf.authKey is not None:
            if not is_strong_password():
                global global_switch
                global_switch = False
                log.info("警告：您的服务器秘钥设置的过于简单，出于安全考虑，不允许使用MAA连接器功能，请您修改您config/server.yaml中的连接秘钥，使其包含至少一个大写字母，一个小写字母，一个数字和一个特殊符号（!@#$%^&*(),.?:{}|<>）。")
            else:
                log.info("还未设置密钥，请设置密钥。")
![图片](https://user-images.githubusercontent.com/107090995/236262000-de5cf62a-d6bf-4c33-853b-300a65a28b3d.png)
不知道这样会不会有问题啊。。

**Comment by desktop4025** [comment]
> 我觉得是你的问题，要不你试试把文件夹改名叫 amiyabot-arknights-hsyhhssyy-maa-1_0

然后我试了试adapter，一点生成密钥就闪退，是不是要用最新的代码啊

**Comment by hsyhhssyy** [comment]
我发一个新的release好了，虽然也不一定能用

**Comment by hsyhhssyy** [comment]
哦，这个秘钥不可以是空的

**Comment by hsyhhssyy** [comment]
后面和maa沟通使用的时候会用到这个秘钥

**Comment by desktop4025** [comment]
> 后面和maa沟通使用的时候会用到这个秘钥

我看看

**Comment by desktop4025** [comment]
> 后面和maa沟通使用的时候会用到这个秘钥

xs这次就弹个log出来直接打不开软件了。。我看看代码出了啥问题
