### ISSUE TITLE
一键长草与自动公招无法使用

### ISSUE THREAD

**Issue by niechy** [hsyhhssyy/amiyabot-arknights-hsyhhssyy-maa#3]
win11，MAA v4.21.0，MAA对接器1.0，AmiyaBotMaaAdapter.v.1.0.1，mumu模拟器12，amiyabotv3.6.4
发送兔兔MAA一键长草，兔兔能正常回应，但在被控端没有联网获取到此任务，单独使用兔兔MAA刷5次1-7可以正常使用
兔兔MAA自动公招，会因为优先级的原因兔兔会说：博士，请发送您的公招界面截图~

**Comment by hsyhhssyy** [comment]
自动公招的问题只能提高优先级。
一键长草没有回应的话，有错误日志吗？

**Comment by niechy** [comment]
兔兔的日志和被控端日志一切正常，我认为是被控端没有接收到maa对接器发送的任务

**Comment by niechy** [comment]
我后来试过手动调节优先级，可以正常使用自动公招
还有佬你在此项目中提供的被控端下载地址下下来的被控端与被控端项目releases中的版本不一样呀，是这边没有改吗

**Comment by hsyhhssyy** [comment]
> 

其实，一键长草实际上的效果是解析上传的GUI.json，然后根据里面的内容，下发一组任务给后端。
所以如果什么都没发生的话，一种可能是界面的gui.json里面的一键长草没有配置任务。

如果你懂查看数据库的话，你能看看数据库里，任务插入进数据库了吗？

被控端版本的话，可能是没有改吧，没事，以版本高的为准。

**Comment by niechy** [comment]
我看到gui是成功上传了

amiyabot的日志
2023-08-06 19:32:28,318
CQHttp
INFO
Bot:1622993790 Channel:884969524 User:1442877592(admin) 一之濑琴美: 兔兔MAA一键长草 
2023-08-06 19:32:36,995
CQHttp
INFO
Bot:1622993790 Channel:832429589 User:1565843245 群萌新: 帮我打下吧 
2023-08-06 19:32:39,811
CQHttp
INFO
Bot:1622993790 Channel:707363255 User:1959773133(admin) 宁雪和: 那就不专 
2023-08-06 19:32:41,618
CQHttp
INFO
Bot:1622993790 Channel:475481644 User:1497151096 既（寄）菜又屑底力又拉的刀客塔（上学）:  
2023-08-06 19:32:45,071
CQHttp
INFO
Bot:1622993790 Channel:707363255 User:1594302360 兔子兔子大兔子: 那就不专 

被控端日志
[2023-08-06T19:31:58][Info      ]成功登录到AmiyaBot Server
[2023-08-06T19:32:00][Info      ]模拟器连接成功。
[2023-08-06T19:32:00][Info      ]正在上传GuiJson
[2023-08-06T19:32:00][Info      ]上传GuiJson完成
plugin.db(我转换成csv的格式了)
"id","uuid","secret","signature","user_id","gui_json"
"1","a01a2ce6-1b58-45a1-9078-84236f9a0bf5","a6bab642-0906-41a0-a219-3899cec67995","i-PRccSsrYxGHr8cAbZmFVoWkbVtLUuzlcMYzKEdho0","1442877592","{
  ""Configurations"": {
    ""Default"": {
      ""Roguelike.RefreshTraderWithDice"": ""False"",
      ""HotKeys"": ""{\""ShowGui\"":{\""Key\"":56,\""Modifiers\"":7},\""LinkStart\"":{\""Key\"":55,\""Modifiers\"":7}}"",
      ""MainFunction.Stage1"": ""1-7"",
      ""GUI.DarkMode"": ""SyncWithOS"",
      ""Guide.StepIndex"": ""4"",
      ""GUI.Placement.Load"": ""True"",
      ""GUI.Placement.SaveOnClosing"": ""True"",
      ""GUI.Placement"": ""{\""Length\"":44,\""Flags\"":0,\""ShowCmd\"":1,\""MinPosition\"":{\""X\"":-1,\""Y\"":-1},\""MaxPosition\"":{\""X\"":-1,\""Y\"":-1},\""NormalPosition\"":{\""Left\"":1263,\""Top\"":291,\""Right\"":2463,\""Bottom\"":1192}}"",
      ""VersionUpdate.name"": ""v4.21.1-alpha.1.d031.g7d3e7a443"",
      ""VersionUpdate.body"": ""\n\n**Full Changelog**: [v4.21.0 -> alpha/v4.21.1-alpha.1.d031.g7d3e7a443](https://github.com/MaaAssistantArknights/MaaAssistantArknights/compare/v4.21.0...alpha/v4.21.1-alpha.1.d031.g7d3e7a443)"",
      ""VersionUpdate.package"": """",
      ""VersionUpdate.isfirstboot"": ""False"",
      ""Infrast.Order.Mfg"": ""0"",
      ""Infrast.Order.Trade"": ""1"",
      ""Infrast.Order.Control"": ""2"",
      ""Infrast.Order.Power"": ""3"",
      ""Infrast.Order.Reception"": ""4"",
      ""Infrast.Order.Office"": ""5"",
      ""Infrast.Order.Dorm"": ""6"",
      ""TaskQueue.Order.WakeUp"": ""0"",
      ""TaskQueue.Order.Recruiting"": ""1"",
      ""TaskQueue.Order.Base"": ""2"",
      ""TaskQueue.Order.Combat"": ""3"",
      ""TaskQueue.Order.Mall"": ""4"",
      ""TaskQueue.Order.Mission"": ""5"",
      ""TaskQueue.Order.AutoRoguelike"": ""6"",
      ""Connect.ConnectConfig"": ""MuMuEmulator12"",
      ""Connect.AdbPath"": ""C:\\Program Files\\Netease\\MuMuPlayer-12.0\\shell\\.\\adb.exe"",
      ""Connect.AddressHistory"": ""[\""127.0.0.1:16384\"",\""127.0.0.1:50833\""]"",
      ""Connect.Address"": ""127.0.0.1:16384"",
      ""Connect.AutoDetect"": ""False"",
      ""Penguin.Id"": ""670549522"",
      ""TaskQueue.WakeUp.IsChecked"": ""True"",
      ""TaskQueue.Recruiting.IsChecked"": ""True"",
      ""TaskQueue.Base.IsChecked"": ""True"",
      ""TaskQueue.Combat.IsChecked"": ""True"",
      ""TaskQueue.Mall.IsChecked"": ""True"",
      ""TaskQueue.Mission.IsChecked"": ""True"",
      ""Connect.TouchMode"": ""minitouch"",
      ""VersionUpdate.VersionType"": ""Nightly"",
      ""Connect.RetryOnDisconnected"": ""True"",
      ""Connect.KillAdbOnExit"": ""True"",
      ""Connect.AlwaysAutoDetect"": ""False"",
      ""Connect.AdbReplaced"": ""True"",
      ""TaskQueue.AutoRoguelike.IsChecked"": ""True"",
      ""GUI.CustomStageCode"": ""False"",
      ""MainFunction.TimesLimited"": ""True"",
      ""MainFunction.TimesLimited.Quantity"": ""11""
    }
  },
  ""Current"": ""Default"",
  ""Global"": {
    ""Timer.Timer1"": ""False"",
    ""Timer.Timer1Hour"": ""0"",
    ""Timer.Timer1Min"": ""0"",
    ""Timer.Timer1.Config"": ""Default"",
    ""Timer.Timer2"": ""False"",
    ""Timer.Timer2Hour"": ""3"",
    ""Timer.Timer2Min"": ""0"",
    ""Timer.Timer2.Config"": ""Default"",
    ""Timer.Timer3"": ""False"",
    ""Timer.Timer3Hour"": ""6"",
    ""Timer.Timer3Min"": ""0"",
    ""Timer.Timer3.Config"": ""Default"",
    ""Timer.Timer4"": ""False"",
    ""Timer.Timer4Hour"": ""9"",
    ""Timer.Timer4Min"": ""0"",
    ""Timer.Timer4.Config"": ""Default"",
    ""Timer.Timer5"": ""False"",
    ""Timer.Timer5Hour"": ""12"",
    ""Timer.Timer5Min"": ""0"",
    ""Timer.Timer5.Config"": ""Default"",
    ""Timer.Timer6"": ""False"",
    ""Timer.Timer6Hour"": ""15"",
    ""Timer.Timer6Min"": ""0"",
    ""Timer.Timer6.Config"": ""Default"",
    ""Timer.Timer7"": ""False"",
    ""Timer.Timer7Hour"": ""18"",
    ""Timer.Timer7Min"": ""0"",
    ""Timer.Timer7.Config"": ""Default"",
    ""Timer.Timer8"": ""False"",
    ""Timer.Timer8Hour"": ""21"",
    ""Timer.Timer8Min"": ""0"",
    ""Timer.Timer8.Config"": ""Default"",
    ""Timer.ForceScheduledStart"": ""False"",
    ""Timer.CustomConfig"": ""False""
  }
}"

**Comment by niechy** [comment]
在今天我更新后输出更详细的信息的情况
我向兔兔发送兔兔MAA一键长草后
amiya-bot的回答：博士，已批量布置了下列任务：，干员们会努力做好罗德岛的日常工作的。

在amiya_plugin.db中的amiyabot-maa-task中是空的
gui.json
```
{
  "Configurations": {
    "Default": {
      "Roguelike.RefreshTraderWithDice": "False",
      "HotKeys": "{\"ShowGui\":{\"Key\":56,\"Modifiers\":7},\"LinkStart\":{\"Key\":55,\"Modifiers\":7}}",
      "MainFunction.Stage1": "1-7",
      "GUI.DarkMode": "SyncWithOS",
      "Guide.StepIndex": "4",
      "GUI.Placement.Load": "True",
      "GUI.Placement.SaveOnClosing": "True",
      "GUI.Placement": "{\"Length\":44,\"Flags\":0,\"ShowCmd\":1,\"MinPosition\":{\"X\":-1,\"Y\":-1},\"MaxPosition\":{\"X\":-1,\"Y\":-1},\"NormalPosition\":{\"Left\":498,\"Top\":97,\"Right\":1698,\"Bottom\":998}}",
      "VersionUpdate.name": "v4.21.1-alpha.1.d060.gd0dc2946d",
      "VersionUpdate.body": "Auto Release of Resource Updates\n\n**Full Changelog**: [v4.21.0 -> alpha/v4.21.1-alpha.1.d060.gd0dc2946d](https://github.com/MaaAssistantArknights/MaaAssistantArknights/compare/v4.21.0...alpha/v4.21.1-alpha.1.d060.gd0dc2946d)",
      "VersionUpdate.package": "",
      "VersionUpdate.isfirstboot": "False",
      "Infrast.Order.Mfg": "0",
      "Infrast.Order.Trade": "1",
      "Infrast.Order.Control": "2",
      "Infrast.Order.Power": "3",
      "Infrast.Order.Reception": "4",
      "Infrast.Order.Office": "5",
      "Infrast.Order.Dorm": "6",
      "TaskQueue.Order.WakeUp": "0",
      "TaskQueue.Order.Recruiting": "1",
      "TaskQueue.Order.Base": "2",
      "TaskQueue.Order.Combat": "3",
      "TaskQueue.Order.Mall": "4",
      "TaskQueue.Order.Mission": "5",
      "TaskQueue.Order.AutoRoguelike": "6",
      "Connect.ConnectConfig": "MuMuEmulator12",
      "Connect.AdbPath": "C:\\Program Files\\Netease\\MuMuPlayer-12.0\\shell\\.\\adb.exe",
      "Connect.AddressHistory": "[\"127.0.0.1:16384\",\"127.0.0.1:50833\"]",
      "Connect.Address": "127.0.0.1:16384",
      "Connect.AutoDetect": "False",
      "Penguin.Id": "670549522",
      "TaskQueue.WakeUp.IsChecked": "True",
      "TaskQueue.Recruiting.IsChecked": "True",
      "TaskQueue.Base.IsChecked": "True",
      "TaskQueue.Combat.IsChecked": "True",
      "TaskQueue.Mall.IsChecked": "True",
      "TaskQueue.Mission.IsChecked": "True",
      "Connect.TouchMode": "minitouch",
      "VersionUpdate.VersionType": "Nightly",
      "Connect.RetryOnDisconnected": "True",
      "Connect.KillAdbOnExit": "True",
      "Connect.AlwaysAutoDetect": "False",
      "Connect.AdbReplaced": "True",
      "TaskQueue.AutoRoguelike.IsChecked": "True",
      "GUI.CustomStageCode": "False",
      "MainFunction.TimesLimited": "True",
      "MainFunction.TimesLimited.Quantity": "11"
    }
  },
  "Current": "Default",
  "Global": {
    "Timer.Timer1": "False",
    "Timer.Timer1Hour": "0",
    "Timer.Timer1Min": "0",
    "Timer.Timer1.Config": "Default",
    "Timer.Timer2": "False",
    "Timer.Timer2Hour": "3",
    "Timer.Timer2Min": "0",
    "Timer.Timer2.Config": "Default",
    "Timer.Timer3": "False",
    "Timer.Timer3Hour": "6",
    "Timer.Timer3Min": "0",
    "Timer.Timer3.Config": "Default",
    "Timer.Timer4": "False",
    "Timer.Timer4Hour": "9",
    "Timer.Timer4Min": "0",
    "Timer.Timer4.Config": "Default",
    "Timer.Timer5": "False",
    "Timer.Timer5Hour": "12",
    "Timer.Timer5Min": "0",
    "Timer.Timer5.Config": "Default",
    "Timer.Timer6": "False",
    "Timer.Timer6Hour": "15",
    "Timer.Timer6Min": "0",
    "Timer.Timer6.Config": "Default",
    "Timer.Timer7": "False",
    "Timer.Timer7Hour": "18",
    "Timer.Timer7Min": "0",
    "Timer.Timer7.Config": "Default",
    "Timer.Timer8": "False",
    "Timer.Timer8Hour": "21",
    "Timer.Timer8Min": "0",
    "Timer.Timer8.Config": "Default",
    "Timer.ForceScheduledStart": "False",
    "Timer.CustomConfig": "False"
  }
}
```

**Comment by hsyhhssyy** [comment]
啊，你这个是Electron版的Gui.json吧，和我的GuiJson长得不一样啊。
话说这个GuiJson不一样的情况下，MAA是怎么能执行刷关的呢？按道理来说，应该是连不上模拟器才对啊。
我在插件那边先改一下看看。

**Comment by hsyhhssyy** [comment]
全新版本的MAA插件发布了，这回改为替换MAA的GUI版本，旧版本的Case逐步关闭了。
