### ISSUE TITLE
无法记录 MAA 设备

### ISSUE THREAD

**Issue by htxzdfunny** [hsyhhssyy/amiyabot-arknights-hsyhhssyy-maa#5]
兔兔版本 `AmiyaBot-v6.4.0` ; MAA 控制器版本 `2.3` ; 运行在 树莓派3b+ 上，系统是 Debian 什么版本我也不知道
在 QQ 群和频道均可复现
具体表现为：其他功能都可正常触发，有回复
只有在记录 MAA 设备时无响应
![图片](https://github.com/hsyhhssyy/amiyabot-arknights-hsyhhssyy-maa/assets/54425771/e256be86-9132-4183-ac7e-27a8586de68f)
![图片](https://github.com/hsyhhssyy/amiyabot-arknights-hsyhhssyy-maa/assets/54425771/ea093d12-4098-47c6-94c9-cd14b2ad77c7)
已确认 MAA 和控制器可以正常通信，也不是因为账号被风控导致消息无法发送
![图片](https://github.com/hsyhhssyy/amiyabot-arknights-hsyhhssyy-maa/assets/54425771/ffec5060-72d3-4e04-bf26-453d9cd767ff)
数据库中有看到设备信息
![图片](https://github.com/hsyhhssyy/amiyabot-arknights-hsyhhssyy-maa/assets/54425771/e49f3a6b-5490-4c13-96a2-f946535970b8)

**Comment by hsyhhssyy** [comment]
你试一下 兔兔记录 MAA 设备
你在记录的时候，没有加前导词，因此没有被兔兔捕捉到。
MAA插件是标准兔兔插件，也要at兔兔或者用兔兔，阿米娅等关键词来触发的。

**Comment by htxzdfunny** [comment]
感谢，问题已解决，确实是因为我少打了个兔兔(
但是上传截图似乎不成功……在学校不方便看，回去再看看

**Comment by hsyhhssyy** [comment]
我盲猜你的网关nginx限制了上传文件的大小（常见问题）。
Nginx默认最大上传1mb，这个是完全不够的，你必须显式配置，加到至少10mb（推荐50mb）
