### ISSUE TITLE
关于项目是否可用与最新版本的maa

### ISSUE THREAD

**Issue by AshdoII** [hsyhhssyy/amiyabot-arknights-hsyhhssyy-maa#6]
想问一下现在该项目是否还在维护。因为我只找到了2.1版本的release，更新日期也都在快1年前了，想知道项目是否还在维护中。
感谢🙏

**Comment by hsyhhssyy** [comment]
可以，因为最新版的MAA内置了远程控制功能，不再需要替换MAA文件。所以旧的连接器不再更新了。
而插件的功能一直也没有新功能加入，所以也没有更新，但是一直是能用的。

**Comment by AshdoII** [comment]
感谢回复，已经开始部署qqbot了，暂等腾讯审核ing。

**Comment by hsyhhssyy** [comment]
如果你使用中遇到问题，欢迎来提issue，这个插件都没什么人用。

**Comment by AshdoII** [comment]
好的，没问题。感谢开发者。
