### ISSUE TITLE
获取密钥出错，错误原因：给定关键字不在字典中。

### ISSUE THREAD

**Issue by AshdoII** [hsyhhssyy/amiyabot-arknights-hsyhhssyy-maa#7]
<img width="1318" alt="image" src="https://github.com/hsyhhssyy/amiyabot-arknights-hsyhhssyy-maa/assets/111554896/0ce3cb29-85a6-4263-b4d9-942517847ba4">
是不是和我的机器人没有过审有关？
AmiyaBot Console实例管理中显示bot运行正常。

**Comment by hsyhhssyy** [comment]
不是，这个连接器没用了.... 现在要连MAA，直接把兔兔的地址填进MAA的远程控制 那一栏里就行了。

![image](https://github.com/hsyhhssyy/amiyabot-arknights-hsyhhssyy-maa/assets/5977110/1aedeb56-6cb2-4da6-a7ee-98e101d44078)

你看一下插件的Readme，应该说的很清楚了吧。

**Comment by AshdoII** [comment]
OK,感谢。
