### ISSUE TITLE
记录MAA设备异常

### ISSUE THREAD

**Issue by Eziodeng** [hsyhhssyy/amiyabot-arknights-hsyhhssyy-maa#8]
兔兔记录MAA设备时，MAA端设置里的用户标识符需要修改为使用bot时的openid？而不是qq号？
修改了一下main.py的逻辑，获取到的data.user_id这里不太对劲，感觉要修改一下代码？
![image](https://github.com/user-attachments/assets/23465038-fdbd-4064-b012-6db0e94764a1)

**Comment by hsyhhssyy** [comment]
官兔接口获取不到qq号，所以只能用openid，所以MAA里也应该填OpenID
这里应该在文档里说清楚的。
